#!/bin/bash

function restart () {
	act=$(date +%s)
	to=$(expr $act + 1200)
	oldframe=$(ratpoison -c "curframe")
	ratpoison -c "gselect xecho"
	ratpoison -c "fselect $FRAME"
	$0 $to $FRAME &
	~/git/xwait/xwait
	ratpoison -c "gselect default"
	ratpoison -c "fselect $oldframe"
	exit 0
}

trap restart USR1

TO_DATE=${1:-`date +%s`}
FRAME=${2:-`ratpoison -c "curframe"`}

while :;
do
	output=""
	if [[ "$TO_DATE" -gt `date +%s` ]]
	then
		output=$(date -u --date @$(($TO_DATE - `date +%s`)) +%M:%S)
	fi
	printf "\f%s" "$output"
	sleep 0.5
done | ~/git/xecho/xecho -stdin
